# Generated by Django 5.0 on 2025-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="can_be_contacted",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="can_data_be_shared",
            field=models.BooleanField(),
        ),
    ]
