# Generated by Django 5.2.4 on 2025-08-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=5000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("frontend", "Front-end"),
                            ("ios", "Ios"),
                            ("android", "Android"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        through="contributor.Contributor", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
