# Generated by Django 5.0 on 2025-08-31 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_contributor"
            ),
        ),
    ]
