# Generated by Django 5.0 on 2025-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_contributor_unique_project_contributor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To do"),
                    ("inprogress", "In Progress"),
                    ("finished", "Finished"),
                ],
                default="todo",
                max_length=15,
            ),
        ),
    ]
