# Generated by Django 5.2.4 on 2025-08-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comment", "0001_initial"),
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="issue.issue"
            ),
        ),
    ]
